### ISSUE TITLE
How to properly link the telegram channel 

### ISSUE THREAD

**Issue by gelordo** [devdetour/TelegramFUSE#5]
Traceback (most recent call last):
  File "/home/george/installs/TelegramFUSE/fuse/../Telegram/main.py", line 18, in <module>
    init()
  File "/home/george/installs/TelegramFUSE/fuse/../Telegram/main.py", line 14, in init
    client = TelegramFileClient(session_name, api_id, api_hash, channel_link)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/george/installs/TelegramFUSE/Telegram/TelegramFUSE.py", line 34, in __init__
    self.channel_entity = self.client.get_entity(channel_link)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/george/.local/lib/python3.11/site-packages/telethon/sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/george/.local/lib/python3.11/site-packages/telethon/client/users.py", line 337, in get_entity
    result.append(await self._get_entity_from_string(x))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/george/.local/lib/python3.11/site-packages/telethon/client/users.py", line 576, in _get_entity_from_string
    raise ValueError(
ValueError: Cannot find any entity corresponding to "https://web.telegram.org/k/#-2030084758"

**Comment by devdetour** [comment]
Hi, try a URL of the form: `https://t.me/<your-channel-id>`.

**Comment by Vercixx** [comment]
you need to get an invitation link from channel's settings, not the link for telegram itself
